package com.campusbalance.analytics.model;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.*;

@Data
@Document(collection = "students")
public class Student {
    @Id
    private String id;
    private String name;
    private String username;
    private String password;

    private String role = "STUDENT"; // STUDENT, FACULTY, ADMIN
    private String department;
    private String batchYear;

    // Semester Lifecycle — a student works inside exactly one active semester at a time.
    // 0 means no active semester right now. Past semesters stay in `semesters` forever,
    // just marked inactive/archived, so they can be revisited from the Profile view.
    private int activeSemesterNumber = 0;
    private List<Semester> semesters = new ArrayList<>();

    // Engagement
    private int totalXP = 0;
    private int dailyStreak = 0;        // consecutive days with a wellness check-in
    private String lastCheckInDate;     // yyyy-MM-dd of the most recent check-in

    @Data
    public static class Assignment {
        private String id; // generated by the server; how the UI refers to one assignment

        @NotBlank(message = "Assignment title is required")
        @Size(max = 100, message = "Assignment title is too long")
        private String title;

        @NotBlank(message = "Pick a subject for the assignment")
        private String subject;

        private String status; // "Pending" or "Completed"

        @Pattern(regexp = "Easy|Medium|Hard", message = "Difficulty must be Easy, Medium or Hard")
        private String difficulty;

        @Min(value = 1, message = "Priority must be between 1 and 5")
        @Max(value = 5, message = "Priority must be between 1 and 5")
        private int priority;

        @NotBlank(message = "Deadline is required")
        @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}(:\\d{2})?)?", message = "Deadline must be a valid date")
        private String deadline;

        private int difficultyWeight;
        private String completedAt;
    }
}
